### ISSUE TITLE
ios module

### ISSUE THREAD

**Issue by zainesmail** [prashantsaini1/titanium-android-imagepicker#16]
I dont see the release version for ios. Please upload it. Thanks

**Comment by m1ga** [comment]
untested but I was able to compile it: http://migaweb.de/ti.imagepicker-iphone-2.0.0.zip
please keep in mind: Ti SDK 8+ only!

**Comment by prashantsaini1** [comment]
ios module added.

**Comment by zainesmail** [comment]
I dont see where the ios module zip was added
