### ISSUE TITLE
Add option to limit the number of selected images

### ISSUE THREAD

**Issue by developer82** [prashantsaini1/titanium-android-imagepicker#2]
Add an optional option (which when provided) gives the developer the option to limit the **maximum** number of images the user can select.
When a user will try to select a number greater than the maximum defined number, he will be shown a toast saying that the limit had been reached.
When a maximum parameter is defined, the number under the title will show the amount of selected images out of the maximum number defined.

**Comment by prashantsaini1** [comment]
Same is planned for next release. I have now total 4 points to be done in next release.

**Comment by developer82** [comment]
Pushed a pull request with this new feature
