### ISSUE TITLE
Android: Allow selection of image folder

### ISSUE THREAD

**Issue by jonasfunk** [prashantsaini1/titanium-android-imagepicker#21]
Just like Facebooks image picker on Android, it would be nice to be able to select an image folder to pick images from.

**Comment by prashantsaini1** [comment]
This module provides basic gallery support, and can be extended to customise the requirements further. I  am quite occupied to create this feature. Any PR are appreciated!

**Comment by jonasfunk** [comment]
I understand. Appreciate what you have done with the gallery.

Sendt fra min iPhone
