### ISSUE TITLE
Add single image select option

### ISSUE THREAD

**Issue by developer82** [prashantsaini1/titanium-android-imagepicker#3]
Add the option to pass and argument stating that the selection is a single select.
In such case, when the user clicks the image, it is automatically selected, calls the callback function and closes the gallery activity.
When using single select mode, there is no need to display the "Proceed" button in the action bar and there is no need to display the selection count label.

**Comment by prashantsaini1** [comment]
It is planned for next release & will keep the same flow of selecting single image & close the gallery. Probably this weekend it will be released.
