### ISSUE TITLE
Add option to customize the text of toast messages

### ISSUE THREAD

**Issue by developer82** [prashantsaini1/titanium-android-imagepicker#5]
The module currently shows some toast messages from time to time.
Add the option to customize those messages just like the labels in the ActionBar.

**Comment by prashantsaini1** [comment]
Can you explain what do you mean by **some toast messages from time to time** ?  I believe there's only 1 toast message in whole module to tell about Storage Permissions.

**Comment by developer82** [comment]
That one and one I've added in awaiting pull request.
