### ISSUE TITLE
Back button does not go back on first click

### ISSUE THREAD

**Issue by developer82** [prashantsaini1/titanium-android-imagepicker#7]
Enter the gallery -> select images -> click the back button in the ActionBar
Expected behavior: The gallery should go back and cancel
Actual behavior: Selection of images is reset to 0

**Comment by prashantsaini1** [comment]
Yes, I made it like that because there's no explicit action to cancel the selection. This is how some other Image Gallery Apps (e.g. WhatsApp) cancel the selected images.
